Extract code and initial dbt transformation
parameshwarbhat411/github-stars-pipeline pull request #3
Opened 2024-06-01 23:51 UTC by parameshwarbhat411

- Updated data ingestion code to load the json from the latest time, 
- Created dbt project and added user, repo, date dimensional model and stg_archive view 
- Created fact_stars and fact_commits view

2024-06-05 00:00 UTC, edsioufi requested changes
Awesome work! 🙌

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +            print(tmp_dir_name.name)
Nit: Let's avoid printing variable values in delivered code. If you wanted to display the temp dir, add context like `f"Temp dir created at {tmp_dir_name}"`

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +                    os.remove(f)
Optional: I'd suggest using

```python
with tempfile.TemporaryDirectory() as tmpdirname:
  ...
```

Which [removes the directory automatically after you exit the with context](https://stackoverflow.com/a/55104228).

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +            tmp_dir_name = tempfile.TemporaryDirectory(dir=temp_dir_path)
Minor: Might be good to pass your `temp_dir_path` for debugging, but in the final code let the tempfile package figure out where to put the files.

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +    temp_dir_path = '/Users/arjunbhat/github-stars-pipeline/data/'
We try to avoid adding local paths to our committed code (it's both specific to your machine + a very minor security risk where you don't want to reveal to the world your local disk file structure lest they use it against you).

You could achieve that here by using a relative path to the source_dir and letting temp_dir give you a temp_dir_path.

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +class ExtractLoad:
Love that you created a class for this!

I'd say add a constructor that takes a `db_path` so that it's a real class? Otherwise we could argue that a function would suffice (`db_path` can be an additional arg to `extract_load`).

You can go either way (function or class) but a class with no instance variables can seem like overkill.

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +            if not table_exists:
Wow incremental loading! Awesome stuff 🔥 

How about instead of doing this if here, having a function `load_json_file` which takes a single json file as input and abstracts away the create or insert logic? In that function, you can check if the table exists. If it doesn't exist, you can then create the table using that json file – which means no need to load that sample json anymore!

As a sidenote here, consider not checking if the table exist, but instead do a `try` to "INSERT INTO" proactively, then capture the right kind of exception from duckdb when a table does not exist, and in that case create the table and re-insert.

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +                if filename.endswith('.json.gz'):
Consider using glob like below here!

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +                    try:
style: Consider splitting to a separate function `extract_json_file`, makes it nicer to read.

2024-06-05 00:00 UTC, edsioufi commented on transform/README.md
Style: Consider removing this boilerplate readme.

2024-06-05 00:00 UTC, edsioufi commented on transform/dbt_project.yml
Style: I'd suggest removing the boilerplate comments that dbt added. More professional that way.

2024-06-05 00:00 UTC, edsioufi commented on load/extract_load.py
> +            json_files = glob.glob(f"{tmp_dir_name.name}/*.json")
I think that there's a bit of duplication of logic here. We already know the names of the files that you included, so there's no need to do another glob here (we know cause we filtered them for extraction). We can just store a list of files (excluding those that errored) and map the name to exclude the .gz.

2024-06-05 00:00 UTC, edsioufi commented on transform/models/marts/dim_date.sql
> +{{ dbt_date.get_date_dimension("1990-01-01", "2050-12-31") }}
Amazing that's an awesome find! Great job 🙌

2024-06-05 00:00 UTC, edsioufi commented on transform/models/marts/dim_repos.sql
> +    SELECT DISTINCT stg_gharchive.repo_id, stg_gharchive.repo_name
Style: I'd remove the `stg_gharchive.` prefix in the case of a single-table select.

2024-06-05 00:00 UTC, edsioufi commented on transform/models/marts/dim_repos.sql
> +SELECT ROW_NUMBER() OVER() as distinct_repo_id,
Smart! Now we can transform this to SCD but let's do it in a subsequent PR!

2024-06-05 00:00 UTC, edsioufi commented on transform/models/marts/dim_users.sql
> +    ROW_NUMBER() OVER() AS user_id,
in this case user be unique (there's no ID unfortunately in the sample data).

2024-06-05 00:00 UTC, edsioufi commented on transform/models/marts/fact_commits.sql
> +JOIN
Great idea to join to dims in the `fact_` to help users navigate this table!
It's not 100% Kimball so I'd suggest at least having one pure fact table, then joining in the downstream aggregated fact tables?

2024-06-05 00:00 UTC, edsioufi commented on transform/models/marts/fact_stars.sql
> +JOIN
Same about joining this early vs. keeping a pure Kimball fact table.

2024-06-05 00:00 UTC, edsioufi commented on transform/models/my_sql.sql
Should this be removed?

2024-06-05 00:00 UTC, edsioufi commented on transform/models/staging/stg_gharchive.sql
> +            ELSE LEFT(type, LENGTH(type) - 5)
Small nit: I'd still keep a replace not a left in this case to make it more explicit that we're removing the "Event" suffix.

2024-06-05 23:57 UTC, parameshwarbhat411 commented on load/extract_load.py
> +            print(tmp_dir_name.name)
Okay Sure

2024-06-05 23:58 UTC, parameshwarbhat411 commented on load/extract_load.py
> +    temp_dir_path = '/Users/arjunbhat/github-stars-pipeline/data/'
Yes, makes sense, I thought of doing that, but forgot

2024-06-05 23:58 UTC, parameshwarbhat411 commented on load/extract_load.py
> +            tmp_dir_name = tempfile.TemporaryDirectory(dir=temp_dir_path)
Sure

2024-06-05 23:59 UTC, parameshwarbhat411 commented on load/extract_load.py
> +class ExtractLoad:
okay understood

2024-06-06 00:00 UTC, parameshwarbhat411 commented on transform/models/marts/dim_users.sql
> +    ROW_NUMBER() OVER() AS user_id,
That's why I have created unique ID for each user with ROW_NUMBER(), is that wrong?

2024-06-06 00:03 UTC, parameshwarbhat411 commented on transform/models/my_sql.sql
Yeah, sorry, I'll properly clean up the code

2024-06-06 00:03 UTC, parameshwarbhat411 commented on transform/models/staging/stg_gharchive.sql
> +            ELSE LEFT(type, LENGTH(type) - 5)
Okay cool

2024-06-21 23:49 UTC, closed without merging